### ISSUE TITLE
The ECDE service needs to be monitored

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/c3s_434_service_monitor#1]
https://climate-adapt.eea.europa.eu/knowledge/european-climate-data-explorer service is new .. but not monitored

**Comment by agstephens** [comment]
@martinjuckes are you aware of the `uptime-robot` stuff that Sam sets up? 

You can add rows here if you want:

https://docs.google.com/spreadsheets/d/1Usepld5HmvSFXyYtQ06ltjyO-E4jYBIla1ciZS4CeNQ/edit#gid=0

And then tell Sam to add them to the service.

**Comment by martinjuckes** [comment]
@agstephens : thanks ... I was going to ask Sam, but I'll add a few rows first. 

We have some functionality which is not restful: pop-ups generated from live maps. I've been looking at Dynatrace as a service which allows to register arbitrary navigation paths and then test them. It works, but it is expensive and cumbersome. It might be easier to go back to James and see if we can make everything restful.

**Comment by martinjuckes** [comment]
This has now been resolved by MARIS.

**Comment by martinjuckes** [comment]
Andrew has removed the monitors installed in October.
